version: '3'
services:
  db:
    build:
      # Dockerfileのあるディレクトリのパスを指定
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      # 公開ポートを指定
      - "3306:3306"
    volumes:
      # 起動時にデータの初期化を行う
      - ./docker/mysql/db:/docker-entrypoint-initdb.d
      # mysqlの永続化
      - ./docker/mysql/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: REST_API
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/github.com/shibuya-yudai/REST_API
    ports:
      - "8080:8080"
    depends_on:
      # dbが先に起動する
      - db
